C++--------------------------------------------------------------------
C Program CIRC_PHOTOM
C To get the photometry of stars in circular apertures
C and visualize on the GRINNEL
C
C Warning the colors do not work since activating the overlays
C disable the cursor...
C
C JLP  Version of 06-11-87
C--------------------------------------------------------------------
	PROGRAM CIRC_PHOTOM
	PARAMETER (IDIM=600)
	REAL*8 SUM_STAR,SUMSQ_SKY,SUM_SKY
	REAL*4 INPUT1(IDIM,IDIM),OUTPUT(IDIM,IDIM)
	REAL*4 NSKY,NSTAR
	INTEGER*2 IXP,IYP,IENT,IF1,IF2
	LOGICAL INPUT_FILE
	CHARACTER NAMEIN1*40,NAMEOUT*40,STAR_NAME*14
	CHARACTER COMMENTS*80
	CHARACTER ANS*1,COLOR*1
	COMMON/IN/INPUT_FILE
 
10	FORMAT(A)
 
	PRINT *,' Program to compute the total intensity',
     1	' within circular apertures'
	PRINT *,' Version of 21-11-87'
 
C Initialization :
	CALL GRINNEL_INIT
	CALL JLP_INQUIFMT
	INPUT_FILE=.TRUE.
 
C Entering the image :
	PRINT *,' INPUT IMAGE DISPLAYED ON THE GRINNEL ?'
	READ(5,10) NAMEIN1
	CALL JLP_READIMAG(INPUT1,NX1,NY1,IDIM,NAMEIN1,COMMENTS)
	LIN1=INDEX(NAMEIN1,'  ')
 
	PRINT *,' EXPOSURE TIME IN SECONDS ? (THE RESULTS ARE DIVIDED',
     1	' BY THIS NUMBER)'
	READ(5,*) EXPOSURE
 
 
15	PRINT *,' OUTPUT FILE WITH THE RESULTS ?'
	READ(5,10) NAMEOUT
	OPEN(2,FILE=NAMEOUT,STATUS='NEW',ERR=15)
	WRITE(2,106)NAMEIN1,EXPOSURE
106	FORMAT(' INPUT IMAGE :',A,/,
     1	' EXPOSURE TIME :',G12.5,/)
	WRITE(2,107)
107	FORMAT(' NAME',T16,'INTENSITY/SEC',T30,
     1	' ERROR',T44,'XCENT',T50,'YCENT',T56,
     1	'STAR DIAM',T68,'SKY DIAM',T80,' SKY',T92,'SIGMA')
 
C Display the cursor:
C	CALL GRZCO(0,1)
C	CALL GRSBFD
 
C Entering the centre :
88	PRINT *,' POSITION THE CURSOR ON THE CENTRE OF THE STAR'
	PRINT *,' TYPE "RETURN" WHEN READY'
	READ(5,10) ANS
 
	CALL GRZCR(0,IXP,IYP,IENT,IF1,IF2)	
	CALL GRSBFD
 
C The origin is 0,0 on the GRINNEL :
	IX0=IXP+1
	IY0=IYP+1
 
	PRINT *,' NAME OF THE STAR ?'
	READ(5,10) STAR_NAME
 
C Now the diameters :
89	PRINT *,' ENTER THE DIAMETERS IN PIXELS FOR THE STAR',
     1	' AND THE SKY :'
	READ(5,*) DIAM1,DIAM2
 
C Drawing the two circles on the screen :
	RAD1=DIAM1/2.
	RAD2=DIAM2/2.
	IRAD1=INT(RAD1)+1
	IRAD2=INT(RAD2)+1
 
C Green :
	COLOR='G'
	CALL GRINNEL_CIRCLE(FLOAT(IX0),FLOAT(IY0),RAD1,COLOR)
	CALL GRINNEL_CIRCLE(FLOAT(IX0),FLOAT(IY0),RAD2,COLOR)
 
C Computing the intensity in 3 iterations to estimate the sky with
c a 2-sigma rejection :
	SIGMA=1.E+12
	SKY=0.
 
	DO IK=1,3
 
	  SUM_SKY=0.D0
	  SUMSQ_SKY=0.D0
	  SUM_STAR=0.D0
	  NSKY=0.
	  NSTAR=0.
 
	  DO IY=IY0-IRAD1,IY0+IRAD1
	    DISTY=FLOAT((IY-IY0)*(IY-IY0))
	     DO IX=IX0-IRAD1,IX0+IRAD1
	       DISTX=FLOAT((IX-IX0)*(IX-IX0))
	       DIST=SQRT(DISTX+DISTY+0.1D-09)
	         IF(DIST.LE.RAD1)THEN
	          NSTAR=NSTAR+1.
	          SUM_STAR=SUM_STAR+INPUT1(IX,IY)
	         ELSEIF(DIST.LE.RAD2)THEN
	          TEST=ABS((INPUT1(IX,IY)-SKY)/2.)
	            IF(TEST.LT.SIGMA)THEN
	              NSKY=NSKY+1.
	              SUM_SKY=SUM_SKY+INPUT1(IX,IY)
	              SUMSQ_SKY=SUMSQ_SKY+INPUT1(IX,IY)*INPUT1(IX,IY)
	            ENDIF
	         ENDIF
	     END DO
	  END DO
	
	SKY=SUM_SKY/NSKY
	SIGMA=SQRT(SUMSQ_SKY/NSKY-SKY*SKY)
	
	END DO
 
C Computing the results :
	TOTAL_INTENSITY=(SUM_STAR-SKY*NSTAR)/EXPOSURE
	SIGMA_STAR=SIGMA*NSTAR/EXPOSURE
	SIGMA_SKY=SIGMA
 
	PRINT 107
	PRINT 101,STAR_NAME,TOTAL_INTENSITY,SIGMA_STAR,
     1	IX0,IY0,DIAM1,DIAM2,SKY,SIGMA_SKY
	WRITE (2,101) STAR_NAME,TOTAL_INTENSITY,SIGMA_STAR,
     1	IX0,IY0,DIAM1,DIAM2,SKY,SIGMA_SKY
101	FORMAT(X,A,T16,G12.5,T30,G12.5,T44,I4,T50,I4,T56,G10.3,T68,
     1	G10.3,T80,G10.3,T92,G10.3)
 
	PRINT *,' DO YOU WANT ANOTHER TRY WITH THE SAME STAR ?(N)'
	READ(5,10) ANS
	IF(ANS.EQ.'Y'.OR.ANS.EQ.'y')THEN
C Erasing the circles:
C	  COLOR='G'
C	  CALL GRINNEL_CLEAR(COLOR)
	  GOTO 89
	ELSE
C Drawing the circles in white :
C	  COLOR='W'
C	  CALL GRINNEL_CIRCLE(FLOAT(IX0),FLOAT(IY0),RAD1,COLOR)
C	  CALL GRINNEL_CIRCLE(FLOAT(IX0),FLOAT(IY0),RAD2,COLOR)
	ENDIF
 
	PRINT *,' DO YOU WANT ANOTHER TRY ANOTHER STAR ?(Y)'
	READ(5,10) ANS
	IF(ANS.NE.'N'.AND.ANS.NE.'n')GOTO 88
 
 
C	PRINT *,' DO YOU WANT TO ERASE ALL THE CIRCLES ?(N)'
C	READ(5,10) ANS
C	IF(ANS.EQ.'y'.OR.ANS.EQ.'Y')THEN
C	 CALL GRINNEL_CLEAR('G')
C	 CALL GRINNEL_CLEAR('W')
C	ENDIF
 
	CALL GRSEND
	CLOSE(2)
	END
C-------------------------------------------------------------
	include 'jlpsub:gri_set.for'
