C++**************************************************************************
C Program READ_MEUDON
C from STRUCBA1 (Version 11-03-87)
C Output file for the details of the input parameters: read_meudon.log
C JLP
C Version 17-03-87
C--**************************************************************************
	PROGRAM READ_MEUDON
C Warning : NLT and NPLT in integer*2 for the header of the CCD file !!!
	INTEGER*2 ILUN,IFUNC,NCARA,IER,ISKIP,NLT,NPLT,INUM(20)
	INTEGER*2 IBUF(2048),LINE(1024)
	LOGICAL*1 IBUFT(4096)
	CHARACTER IDENT*80,FICH1*20,FICH2*20
	CHARACTER*80 KDENT(20),SFICH(20)*20
	EQUIVALENCE (IBUF(1),IBUFT(1))
	COMMON /BLOC1/ILUN
 
10	FORMAT(A)
	IFUNC=5
C Each block has 4096 octets
	NCARA=4096
	PRINT *,' (YOU SHOULD HAVE TYPED:'
	PRINT *,' $ASSIGN MUA0: CCD'
	PRINT *,' $MOU/FOR MUA0:)'
	PRINT *,' '
C IFUNC=5 : MONTAGE DE LA BANDE NOM LOGIQUE: CCD
	CALL MTACCESS(ILUN,IFUNC,IBUFT,NCARA,0,IER,'CCD')
	PRINT *,' ILUN= ',ILUN
	PRINT *,' NCARA= ',NCARA
	PRINT *,' IER= ',IER
	IF(IER.NE.0)PRINT *,'PROBLEME AU MONTAGE'
C IFUNC=1 : REMBOBINAGE A TOUT HAZARD...
	IFUNC=1
	CALL MTACCESS(ILUN,IFUNC,IBUFT,NCARA,0,IER,'CCD')
	OPEN(3,STATUS='unknown',FILE='read_meudon.log')
	PRINT 1015
1015	FORMAT(/)
	PRINT *,' NOMBRE DE FICHIERS A LIRE SUR LA BANDE  (20 MAX)'
	READ(5,*) NFICH
	PRINT 1015
	PRINT *,' DONNER LES NUMEROS DE FICHIERS  PAR ORDRE CROISSANT'
	PRINT 1015
	DO 250 IF=1,NFICH
	PRINT 270,IF
270	FORMAT(I4,'    FICHIER BANDE NUMERO:',$)
	READ(5,*) NUM
	PRINT 271
271	FORMAT(' NOM A DONNER AU FICHIER DISQUE:',$)
	READ(5,10) FICH1
	PRINT *,' COMMENTAIRE POUR CE FICHIER:'
	READ(5,10) KDENT(IF)
	INUM(IF)=NUM
	SFICH(IF)=FICH1
250	CONTINUE
	PRINT 1015
	PRINT *,'  DETAIL DES OPERATIONS DS LE FICHIER: read_meudon.log'
	PRINT 1015
	WRITE(3,217)
217	FORMAT(/,'-------------    DETAIL DES OPERATIONS---------------',//)
 
 
C Format 1 (Meudon) 256 particules, 16 octets par particule,
C Blocks de 4096 octets
	DO 251 NF=1,NFICH
	NUFIN=INUM(NF)
	NSAUT=NUFIN-1
C Skipping some files (Tape marks EOF) :
	IF(NSAUT.GT.0)THEN
	IFUNC=3
	CALL MTACCESS(ILUN,IFUNC,IBUFT,NCARA,NSAUT,IER,'CCD')
	IF(IER.NE.0)PRINT *,' PB AVEC LE SAUT DE FICHIERS'
	ENDIF
 
C Opening the output file : (74 lines of 256 pixels)
	FICH2=SFICH(NF)
	VINIT=(768*74)/256.
	INIT=NINT(VINIT)+1
262	OPEN(1,FILE=FICH2,STATUS='NEW',
     1	INITIALSIZE=-INIT,ERR=1003)
	WRITE(3,260) NUFIN,FICH2
260	FORMAT(' NUMERO FICHIER BANDE:',I3,9X,' NOM SUR DISQUE:',A20)
	PRINT 260,NUFIN,FICH2
	GO TO 255
 
C Set the name of the file if problem when opening it
1003	WRITE(3,261) NUFIN
261	FORMAT(/,' LE FICHIER ',I3,' A POUR NOM: FOR001.DAT')
	FICH2='FOR001.DAT'
	GO TO 262
 
255	CONTINUE
 
	DO IBLOCK=1,74
 
C Reading the tape into IBUFT (IFUNC=2)
	IFUNC=2
	CALL MTACCESS(ILUN,IFUNC,IBUFT,NCARA,0,IER,'CCD')
	IF(IER.NE.0)PRINT *,' PB LORS DE LA LECTURE'
C In Format 1 (Meudon) : X,Y,Z,0,0,0,0,0  (only 3/8 are used)
	KK=0
 	  DO K=1,256
	  K1=(K-1)*8 +1
	  KK=KK+1
	  LINE(KK)=IBUF(K1)
	  KK=KK+1
	  K1=K1+1
	  LINE(KK)=IBUF(K1)
	  KK=KK+1
	  K1=K1+1
	  LINE(KK)=IBUF(K1)
	  END DO
 
	WRITE(1,*) (LINE(KK),KK=1,768)
 
	END DO
 
251	CONTINUE
 
C End :
	CLOSE(1)
	CALL MTACCESS(ILUN,1,IBUFT,NCARA,0,IER,'CCD')
	STOP
	END
 
C-----------------------------------------------------------------
C DOC MTACCESS :
C CETTE ROUTINE TRAVAILLE SUR LES BANDES MAGNETIQUES EN
C MODE PHYSIQUE.
C OPERATIONS:
C		IFUNC=1 --> REMBOBINAGE
C		IFUNC=2 --> LECTURE D'UN ENREGISTREMENT
C		IFUNC=3 --> SKIP DE "ISKIP" FICHIERS (TAPE MARK)
C		IFUNC=4 --> ECRITURE D'UN ENREGISTREMENT
C		IFUNC=5 --> ASSIGNATION D'UN LUN A UN "LOGICAL"
C		IFUNC=6 --> ECRITURE FIN DE FICHIER (TAPE MARK)
C
C	APPEL:
C
C	CALL MTACCESS (ILUN,IFUNC,IBUF,INCAR,ISKIP,IEOF,DEVNAM)
C
C
C	ILUN= NO. UNITE LOGIQUE ASSIGNEE A UN NOM "LOGICAL"
C		INTEGER*2
C
C	IFUNC=FONCTION A REALISER SUR LA BANDE
C		INTEGER*2
C
C	IBUF = BUFFER EN ENTREE OU EN SORTIE
C		LOGICAL*1
C
C	INCAR=NOMBRE DE CARACTERES EN ENTREE OU SORTIE < 32767 CAR.
C		INTEGER*2
C
C	ISKIP=NOMBRE DE FICHIERS A SKIPER >0 EN AVANT , <0 EN ARRIERE
C	DANS CE CAS ON EST JUSTE A LA FIN D'UN FICHIER .
C	LE NOMBRE DE FICHIERS EST PHYSIQUE (I.E NOMBRE DE TAPE MARK)
C		INTEGER*2
C
C	IEOF : CODE RETOUR D'UNE FONCTION DECRITE CI-DESSUS
C		INTEGER*2
C
C	IEOF=1   INDICATEUR FIN DE FICHIER EN ENTREE
C	    =2   ERREUR DE LONGUEUR EN LECTURE DONNEE<REELLE
C	    =3   ERREUR DE PARITE EN LECTURE
C	    =4   FIN DE BANDE PHYSIQUEMENT
C	    =5   VOLUME NON MONTEE MAIS ASSIGNE AVEC UN LOGICAL
C	    =6   DATA CHECK EN ECRITURE (VOIR MAINTENANCE)
C	    =7   FIN DE VOLUME I.E DEUX 'TAPE MARK'
C
C
C	DEVNAM= NOM "LOGICAL" ASSIGNE AU MOMENT DU MOUNT DE LA BANDE
C		CHARACTER* DEVNAM   *=LONGUEUR DU NOM DONNE AU MOMENT
C				      DU MOUNT DE LA BANDE
C
C
C CE PROGRAMME TRAVAILLERA AVEC LE NOM "LOGICAL" DONNE AU MOUNT
C
C
C
C
C***********************************************************************
C
C            EXEMPLE D'UTILISATION DU PROGRAMME :
C	A) LES DECLARATIONS DANS LE PROGRAMME APPELANT :
C		INTEGER*2 ILUN,IFUNC,INCAR,ISKIP,IEOF
C		LOGICAL*1 IBUF( )  ! DONNER LONGUEUR DE IBUF
C		CHARACTER*5 DEVNAM ! ICI 5 CAR LE "LOGICAL" EST TAPE1
C		DATA DEVNAM/'TAPE1'/ ! LE NOM "LOGICAL" ASSIGNE AU MOUNT
C                      		.......
C				........
C 	B) IL FAUT FAIRE LA CORRESPONDANCE POUR AVOIR LE NO. LOGIQUE
C	                   DE ILUN DONNE PAR LE SYSTEME
C		IFUNC=5		! FONCTION ASSIGNATION
C		CALL MTACCESS(ILUN,IFUNC,IBUF,INCAR,ISKIP,IEOF,DEVNAM)
C		!!!!!ATTENTION IL NE FAUT PAS DETRUIRE  ..ILUN...
C		!!!!! IL SERVIRA POUR TOUTE LA SUITE DE VOS OPERATIONS
C				.......
C				........
C		!  MAINTENANT VOUS POUVEZ EXECUTER TOUTES LES AUTRES
C		!  FONCTIONS A VOTRE SOUHAIT ...............
C		! ..........................................
C	C) MAINTENANT IL FAUT LINKER AVEC VOTRE PROGRAMME :
C
C		LINK PROG,.........,'UTL'/LIBRARY
C 		PROG EST VOTRE PROGRAMME
C		............ET LES AUTRES MODULES DE VOTRE ENSEMBLE
C		'UTL'/LIBRARY   LA LIBRAIRIE DES UTILITAIRES DE MEUDON
C
C
C	D) A L'EXECUTION AVANT DE FAIRE LE RUN EXECUTER :
C		- ALLOCATE MT:
C		-MOU 'DEV'/FOR/DENSITY=XXXX
C		-ASSIGN 'DEV' "LOGICAL"
C
C 		'DEV' UNITE ALLOUEE
C		XXXX  LA DENSITE DESIREE
C		"LOGICAL" LE NOM "LOGICAL" DEFINI DANS VOTRE PROG......
C
C
C***********************************************************************
C
C-----------------------------------------------------------------
	include 'jlpsub:mtaccess.for'
