C++--------------------------------------------------------------------
C BADCOLUMN
C Set of subroutines to correct from badcolumns :
C  1, 2, or 3 adjacent bad columns
C
C JLP Version of 17-03-86
C--------------------------------------------------------------------
 
C++*********************************************************************
C	SUBROUTINE BADCOLUMN1
C	MATRIX:
C		0.5  0.  0.5
C		1.0  0.  1.0
C		0.5  0.  0.5
C--*********************************************************************
	SUBROUTINE BADCOLUMN1(IMAGE,NPL,NL,IBADC)
	PARAMETER (IDIM=600)
	REAL*4 IMAGE(IDIM,IDIM)
 
	DO ILINE=1,NL
	  IM1=MAX(ILINE-1,1)
 	  IP1=MIN(ILINE+1,NL)
	  X=0.5*(IMAGE(IBADC-1,IM1)+IMAGE(IBADC-1,IP1)+
	1	IMAGE(IBADC+1,IM1)+IMAGE(IBADC+1,IP1))
	  X=((X+IMAGE(IBADC-1,ILINE)+IMAGE(IBADC+1,ILINE))/4.)
	  IMAGE(IBADC,ILINE)=X
	END DO
 
	RETURN
	END
 
C++*********************************************************************
C	SUBROUTINE BADCOLUMN2
C	MATRIX FOR THE FIRST COLUMN :
C		0.6  0.0  0.0  0.4
C		1.2  0.0  0.0  0.8
C		0.6  0.0  0.0  0.4
C	AND ITS CHIRAL FORM FOR THE SECOND COLUMN.
C--*********************************************************************
	SUBROUTINE BADCOLUMN2(IMAGE,NPL,NL,IBADC)
	PARAMETER (IDIM=600)
	REAL*4 IMAGE(IDIM,IDIM)
 
	DO ILINE=1,NL
	  IM1=MAX(ILINE-1,1)
	  IP1=MIN(ILINE+1,NL)
 
	  SUMM=IMAGE(IBADC-1,IM1)*IMAGE(IBADC-1,IM1)
	1	+IMAGE(IBADC-1,IP1)*IMAGE(IBADC-1,IP1)
	1	+IMAGE(IBADC+2,IM1)*IMAGE(IBADC+2,IM1)
	1	+IMAGE(IBADC+2,IP1)*IMAGE(IBADC+2,IP1)
	1	+IMAGE(IBADC-1,ILINE)*IMAGE(IBADC-1,ILINE)
	1	+IMAGE(IBADC+2,ILINE)*IMAGE(IBADC+2,ILINE)
	  SUMM=SUMM/6.
 
	  XMEAN=IMAGE(IBADC-1,IM1)+IMAGE(IBADC-1,IP1)+
	1	IMAGE(IBADC+2,IM1)+IMAGE(IBADC+2,IP1)+
	1	IMAGE(IBADC-1,ILINE)+IMAGE(IBADC+2,ILINE)
	  XMEAN=XMEAN/6.
 
	  STDEV=SQRT(SUMM-XMEAN*XMEAN)
 
	  X=0.6*(IMAGE(IBADC-1,IM1)+IMAGE(IBADC-1,IP1))+
	1	0.4*(IMAGE(IBADC+2,IM1)+IMAGE(IBADC+2,IP1))
	  X=(X+1.2*IMAGE(IBADC-1,ILINE)+
	1	0.8*IMAGE(IBADC+2,ILINE))/4.
C	  IMAGE(IBADC,ILINE)=G05DDF(X,STDEV)
          CALL JLP_RANDOM_GAUSS(WORK)
	  IMAGE(IBADC,ILINE)=X+STDEV*WORK
 
	  X=0.4*(IMAGE(IBADC-1,IM1)+IMAGE(IBADC-1,IP1))+
	1	0.6*(IMAGE(IBADC+2,IM1)+IMAGE(IBADC+2,IP1))
	  X=(X+0.8*IMAGE(IBADC-1,ILINE)+
	1	1.2*IMAGE(IBADC+2,ILINE))/4.
C	  IMAGE(IBADC+1,ILINE)=G05DDF(X,STDEV)
          CALL JLP_RANDOM_GAUSS(WORK)
	  IMAGE(IBADC+1,ILINE)=X+STDEV*WORK
 
	END DO
 
	RETURN
	END
C++*********************************************************************
C	SUBROUTINE BADCOLUMN3
C	MATRIX FOR THE FIRST COLUMN :
C		0.6  0.0  0.0  0.0  0.4
C		1.2  0.0  0.0  0.0  0.8
C		0.6  0.0  0.0  0.0  0.4
C	AND ITS CHIRAL FORM FOR THE THIRD COLUMN.
C--*********************************************************************
	SUBROUTINE BADCOLUMN3(IMAGE,NPL,NL,IBADC)
	PARAMETER (IDIM=600)
	REAL*4 IMAGE(IDIM,IDIM)
 
	DO ILINE=1,NL
	  IM1=MAX(ILINE-1,1)
	  IP1=MIN(ILINE+1,NL)
 
	  SUMM=IMAGE(IBADC-1,IM1)*IMAGE(IBADC-1,IM1)
	1	+IMAGE(IBADC-1,IP1)*IMAGE(IBADC-1,IP1)
	1	+IMAGE(IBADC+3,IM1)*IMAGE(IBADC+3,IM1)
	1	+IMAGE(IBADC+3,IP1)*IMAGE(IBADC+3,IP1)
	1	+IMAGE(IBADC-1,ILINE)*IMAGE(IBADC-1,ILINE)
	1	+IMAGE(IBADC+3,ILINE)*IMAGE(IBADC+3,ILINE)
	  SUMM=SUMM/6.
 
	  XMEAN=IMAGE(IBADC-1,IM1)+IMAGE(IBADC-1,IP1)+
	1	IMAGE(IBADC+3,IM1)+IMAGE(IBADC+3,IP1)+
	1	IMAGE(IBADC-1,ILINE)+IMAGE(IBADC+3,ILINE)
	  XMEAN=XMEAN/6.
 
	  STDEV=SQRT(SUMM-XMEAN*XMEAN)
 
	  X=0.6*(IMAGE(IBADC-1,IM1)+IMAGE(IBADC-1,IP1))+
	1	0.4*(IMAGE(IBADC+3,IM1)+IMAGE(IBADC+3,IP1))
	  X=(X+1.2*IMAGE(IBADC-1,ILINE)+
	1	0.8*IMAGE(IBADC+3,ILINE))/4.
C	  IMAGE(IBADC,ILINE)=G05DDF(X,STDEV)
          CALL JLP_RANDOM_GAUSS(WORK)
	  IMAGE(IBADC,ILINE)=X+STDEV*WORK
 
C Mean X, std dev STDEV
C random real number taken from a Gaussian distribution
C Cf BRENT, R.P. Algorithm 488 C.A.C.M. ,p704, 1974
 
	  X=0.5*(IMAGE(IBADC-1,IM1)+IMAGE(IBADC-1,IP1))+
	1	0.5*(IMAGE(IBADC+3,IM1)+IMAGE(IBADC+3,IP1))
	  X=(X+IMAGE(IBADC-1,ILINE)+
	1	IMAGE(IBADC+3,ILINE))/4.
C	  IMAGE(IBADC+1,ILINE)=G05DDF(X,STDEV)
          CALL JLP_RANDOM_GAUSS(WORK)
	  IMAGE(IBADC+1,ILINE)=X+STDEV*WORK
 
	  X=0.4*(IMAGE(IBADC-1,IM1)+IMAGE(IBADC-1,IP1))+
	1	0.6*(IMAGE(IBADC+3,IM1)+IMAGE(IBADC+3,IP1))
	  X=(X+0.8*IMAGE(IBADC-1,ILINE)+
	1	1.2*IMAGE(IBADC+3,ILINE))/4.
C	  IMAGE(IBADC+2,ILINE)=G05DDF(X,STDEV)
          CALL JLP_RANDOM_GAUSS(WORK)
	  IMAGE(IBADC+2,ILINE)=X+STDEV*WORK
 
	END DO
 
	RETURN
	END
