C*****************************************************************
C Short plotting program to test NEWPLOT2
C
C JLP
C Version: 18-07-2007
C---------------------------------------------------------------------
        PROGRAM TEST_NEWPLOT2
        IMPLICIT NONE
        INTEGER IDIM,KCUR_MAX,NOUT_MAX
	PARAMETER (IDIM=200,KCUR_MAX=4, NOUT_MAX=20)
	REAL X(IDIM,KCUR_MAX),Y(IDIM,KCUR_MAX)
        REAL ERRX(IDIM,KCUR_MAX),ERRY(IDIM,KCUR_MAX)
	REAL XOUT(NOUT_MAX),YOUT(NOUT_MAX)
        REAL XMIN,XMAX,YMIN,YMAX,EXPAND
	INTEGER NPTS(IDIM),FULL_CAPTION
	CHARACTER CHAR1*80,CHAR2*80,CHAR3*80
	CHARACTER PLOTDEV*40,FILENAME*60,COMMENTS*80
	CHARACTER NCHAR(3)*4,PCOLOR(2)*30
	INTEGER I,KCURVE,ERROR_BARS,NOUT,IDEV,AUTO_SCALE,IPLAN
        INTEGER Y_IS_REVERSED,TICKS_IN,JLP_AXES
        INTEGER X_IS_LOG10,Y_IS_LOG10,XGRID_IS_WANTED,YGRID_IS_WANTED
 
C X_IS_LOG10 = 0 if linear, 1 if log10
C Y_IS_LOG10 = 0 if linear, 1 if log10
        X_IS_LOG10 = 1
        Y_IS_LOG10 = 1

	XMIN=0.1
	XMAX=11
        IF(X_IS_LOG10 .EQ. 1)THEN
	  XMIN=LOG10(XMIN)
	  XMAX=LOG10(XMAX)
        ENDIF
	YMIN=10002
	YMAX=1.
        IF(Y_IS_LOG10 .EQ. 1)THEN
	  YMIN=LOG10(YMIN)
	  YMAX=LOG10(YMAX)
        ENDIF

C First curve:
        X(1,1) = 2.
        Y(1,1) = 20.
        X(2,1) = 2.
        Y(2,1) = 30.
        IF(X_IS_LOG10 .EQ. 1)THEN
          X(1,1) = LOG10(X(1,1)) 
          X(2,1) = LOG10(X(2,1)) 
        ENDIF
        IF(Y_IS_LOG10 .EQ. 1)THEN
          Y(1,1) = LOG10(Y(1,1)) 
          Y(2,1) = LOG10(Y(2,1)) 
        ENDIF
	NPTS(1)=2
	WRITE(NCHAR(1),11) '92',CHAR(0)
11      FORMAT(A2,A1)
        PCOLOR(1)='RGB_100_100_0'
        PCOLOR(1)='Green'

C Second curve:
	NPTS(2)=100
	DO I=1,NPTS(2)
	  X(I,2)= FLOAT(I)
	  Y(I,2)=X(I,2)**2
	END DO
        IF(X_IS_LOG10 .EQ. 1)THEN
	  DO I=1,NPTS(2)
	    X(I,2)= LOG10(X(I,2))
          END DO
        ENDIF
        IF(Y_IS_LOG10 .EQ. 1)THEN
	  DO I=1,NPTS(2)
	    Y(I,2)=LOG10(Y(I,2))
          END DO
        ENDIF
	WRITE(NCHAR(2),11) '41',CHAR(0)
        PCOLOR(2)='Purple'
C
	WRITE(CHAR1,12) 'label: x',CHAR(0)
	WRITE(CHAR2,12) 'label: x^2',CHAR(0)
	WRITE(CHAR3,12) 'Test of newplot2',CHAR(0)
	WRITE(FILENAME,12) 'filename',CHAR(0)
	WRITE(COMMENTS,12) 'comments',CHAR(0)
C To display date, filename, and comments:
        FULL_CAPTION=1
C	PRINT *,' Plotdevice ? (xterm, postscript)'
C	READ(5,10) PLOTDEV
10	FORMAT(A)
C	WRITE(PLOTDEV,12) 'xterm',CHAR(0)
	WRITE(PLOTDEV,12) 'square',CHAR(0)
12      FORMAT(A,A1)
	ERROR_BARS=0
	KCURVE=2
	WRITE(6,*) ' X1,Y1,X2,Y2',XMIN,YMIN,XMAX,YMAX
 
        AUTO_SCALE=0
        IPLAN=0
        Y_IS_REVERSED=0
        JLP_AXES=0
        EXPAND=1.2
C 
	CALL JLP_SPDEVICE_CURVE(PLOTDEV,XMIN,XMAX,YMIN,YMAX,IPLAN,
      1                         CHAR3,IDEV)
C
        I=1
        IF(I.EQ.1)THEN
	CALL NEWPLOT2(X,Y,ERRX,ERRY,NPTS,IDIM,KCURVE,XMIN,XMAX,
     1  YMIN,YMAX,AUTO_SCALE,IPLAN,Y_IS_REVERSED,CHAR1,CHAR2,CHAR3,
     1  NCHAR,PCOLOR,XOUT,YOUT,NOUT,NOUT_MAX,ERROR_BARS,
     1  FILENAME,COMMENTS,FULL_CAPTION,EXPAND,TICKS_IN,IDEV)
        ELSE 
        XGRID_IS_WANTED=0
        YGRID_IS_WANTED=0
	CALL NEWPLOT21(X,Y,ERRX,ERRY,NPTS,IDIM,KCURVE,XMIN,XMAX,
     1  YMIN,YMAX,AUTO_SCALE,IPLAN,Y_IS_REVERSED,CHAR1,CHAR2,
     1	CHAR3,NCHAR,PCOLOR,XOUT,YOUT,NOUT,NOUT_MAX,ERROR_BARS,FILENAME,
     1  COMMENTS,FULL_CAPTION,JLP_AXES,XGRID_IS_WANTED,YGRID_IS_WANTED,
     1  X_IS_LOG10,Y_IS_LOG10,EXPAND,TICKS_IN,IDEV)
        ENDIF
 
        CALL JLP_SPCLOSE(IDEV)
	STOP
	END
