##############################################################################
# Makefile for SOURCE
# to generate executable version of JLP fortran programs
# JLP
# Version 12-11-90
##############################################################################
SOURCE=$(HOME)/source
midir=$(JLPLIB)/midas
nagdir=/usr1/midas/90MAY/lib
mylib=$(JLPLIB)/jlp
smgolib=$(JLPLIB)/smgo
JLIB=$(JLPLIB)/math/conju_grad.o $(mylib)/jlpacc.a $(mylib)/jlputil.a \
     $(mylib)/newplot0.a $(mylib)/jlp_splot1.a $(mylib)/jlp_splot2.a \
     $(mylib)/jlpacc.a 
XLIB= -lX11
######################################################
# For Sun and Dec (and Pic du Midi):
LIBC=
# WARNING: For IBM use libc !!!!!!!!!!!!!!!!!!
##############################################
#LIBC= /lib/libc.a
#XLIB= -lXaw -lXmu -lXt -lX11
F77=f77
F77LIB=/usr/lib/libF77.a /usr/lib/libI77.a /usr/lib/libU77.a 
#MIDLIB=$(nagdir)/tbllib.a $(midir)/stlib.a $(midir)/oslib.a
MIDLIB=$(midir)/stlib.a $(midir)/udiolib.a $(midir)/oslib.a
#MATHLIB=/usr1/midas/91MAY/lib/mathlib.a
##MATHLIB = $(JLPLIB)/math/mymath.a $(JLPLIB)/math/jlp_math.o 
MATHLIB =
INC=.
FFLAGS=-g
#	$(F77) $(FFLAGS) -o $(EXEC)/$*.exe $*.o \
#	$(JLIB) $(MATHLIB) $(MIDLIB) $(XLIB) $(LIBC)
#	rm $*.f

.SUFFIXES:
.SUFFIXES:  .o .for .exe $(SUFFIXES) 

.for.exe:
	$(EXEC)/esoext1.exe -I ../jlpsub -f $*.for
	$(F77) -c $(FFLAGS) $*.f
	$(F77) $(FFLAGS) -o $(EXEC)/$*.exe $*.o \
	$(JLIB) $(MATHLIB) $(MIDLIB) $(XLIB) $(LIBC)
	rm $*.o

.o.exe:
	$(F77) $(FFLAGS) -o $(EXEC)/$*.exe $*.o \
	$(JLIB) $(MATHLIB) $(MIDLIB) $(XLIB) $(LIBC)
	rm $*.o

all: $*.exe
$*.exe : $*.o $*.for
	@ sleep
