C++**************************************************************
C PLAGAL_BATCH
C
C Removes the galaxy from a CCD image. Derived from PLAGAL,
C for batch jobs. Only option 1 is available (subtraction of
C a smoothed profile).
C Reads the parameters from the header of the profile.
C
C SYNTAX:
C      RUNS PLAGAL_BATCH in_image out_image profile
C             min_radius,max_radius order_of_the_polynomial
C
C Example:
C      RUNS PLAGAL_BATCH test test_REM test.pro 5.,100. 5
C
C Nota1: min_radius,max_radius in arcsec define the boundaries
C        for the fit of the profile.
C Nota2: the fit is generally good with a 5th or 7th order polynomial
C        (fitting in log/log).
C
C JLP
C Version of 05/03/97 
C--**************************************************************
	PROGRAM PLAGAL_BATCH
	PARAMETER (IDIM1=2000)
	REAL*8 VRAD,VPRO
	REAL*4 RAD2,AXRATIO2
	INTEGER*4 PNTR_IN,PNTR_OUT
	CHARACTER NAMEPRO*40,NAMEIN*40,NAMEOUT*40,ANS*1,COMMENTS*80
	LOGICAL FIXED_ELLI
	INTEGER*4 MADRID(1)
	COMMON /VMR/MADRID
	COMMON/PLG1_PARAM/RADMIN,RADMAX,X0,Y0,SCALE,SKY,VPRO(IDIM1),
     1	VRAD(IDIM1),NPTS,RAD2(100),AXRATIO2(100),NPOINT2
	COMMON/FIXELLIP/UU,VV,WW,AXRATIO,CO,SI
 
10	FORMAT(A)
	CALL JLP_BEGIN
 
C Open 10 which is used in POLYFIT
	OPEN(10,FILE='plagal.tmp',STATUS='unknown')
 
C Open "plagal.log" to keep a trace of what has been done:
	OPEN(9,FILE='plagal.log',STATUS='unknown',
     1	ACCESS='SEQUENTIAL')
 
C Write the title :
	WRITE(9,81)
	PRINT 81
81	FORMAT(' PROGRAM PLAGAL_BATCH - Version of 05/03/97-',/)
 
C Inquires about the format of the files :
	CALL JLP_INQUIFMT
 
C Input of the names of the files:
	PRINT *,' INPUT IMAGE ?'
	READ(5,10) NAMEIN
 
	CALL JLP_VM_READIMAG(PNTR_IN,NX,NY,NAMEIN,COMMENTS)
	WRITE(9,82)NAMEIN
82	FORMAT(' INPUT IMAGE : ',A)
 
	PRINT *,' OUTPUT IMAGE ?'
	READ(5,10) NAMEOUT
 
C Get dynamical memory for the output:
	CALL JLP_GETVM(PNTR_OUT,NX*NY*4)
 
	PRINT *,' INPUT PROFILE :'
	READ(5,10) NAMEPRO
 
C Other options
	PRINT *,' MINIMUM AND MAXIMUM RADII FOR THE FIT ? (ARCSEC)'
	READ(5,*) RADMIN,RADMAX
	PRINT *,' ORDER OF THE POLYNOMIAL ?'
	READ(5,*) KORDER
 
C Read the parameter file :
	CALL READ_PARAM(NAMEPRO)
 
C Output the values in "plagal.log" :
	WRITE(9,73)FICH3,NPTS
73	FORMAT(' INPUT PROFILE :',A,' NPTS =',I6)
	WRITE(9,84)SCALE,XPHI,X0,Y0,SKY,AXRATIO
84	FORMAT(' SCALE : ',G12.4,' ORIENTATION :',G12.4,/,
     1	' CENTRE : OX,OY ',G12.4,2X,G12.4,/,
     1	' SKY LEVEL :',G12.4,' AXIS RATIO :',G12.4)
	
C We take a smaller value for the sky (for a better fit):
	SKY=SKY-10.
	WRITE(9,85) SKY
85	FORMAT(' We take a smaller value for the sky (for a better fit)',
     1	/,' New sky level:',G12.4)
 
C Only fixed ellipticity available in Batch mode
	FIXED_ELLI=.TRUE.
	
C Subtracting the galaxy :
	CALL PLAGAL1(MADRID(PNTR_IN),MADRID(PNTR_OUT),NX,NY,NX,
     1	FIXED_ELLI,KORDER)
 
C Writing the output file with comments :
	LPRO=INDEX(NAMEPRO,' ')-1
	WRITE(COMMENTS,303)NAMEPRO(1:LPRO)
303	FORMAT(' PLAGAL_BATCH WITH SMOOTHED PROFILE : ',A,' //')
	CALL JLP_WRITEIMAG(MADRID(PNTR_OUT),NX,NY,NX,NAMEOUT,COMMENTS)
 
C End :
	CLOSE(9)
	CLOSE(10)
	PRINT *,' Logfile in "plagal.log"'
	CALL JLP_END
	STOP
	END
C*************************************************************
C Subroutine to read the parameters of the galaxy in the header of
C the profile, as generated by "PROFILE1"
C (For the format, see "PROFILE1.DOC")
C
C*************************************************************
	SUBROUTINE READ_PARAM(NAMEPRO)
	PARAMETER (IDIM1=2000)
	REAL*8 VRAD,VPRO
	REAL*4 RAD2,AXRATIO2,PI
	CHARACTER NAMEPRO*40,BUFFER*80
	COMMON/PLG1_PARAM/RADMIN,RADMAX,X0,Y0,SCALE,SKY,VPRO(IDIM1),
     1	VRAD(IDIM1),NPTS,RAD2(100),AXRATIO2(100),NPOINT2
	COMMON/FIXELLIP/UU,VV,WW,AXRATIO,CO,SI
        PI=3.14159265
 
10	FORMAT(A)
 
	OPEN(3,FILE=NAMEPRO,STATUS='OLD',ERR=999)
 
C Get the right position (jumping 4 items) in the file:
	 DO I=1,8
	  READ(3,10,ERR=999)BUFFER
	 END DO
 
C Read the position angle of the ellipses in degrees
	 READ(3,10,ERR=999)BUFFER
	 READ(3,*,ERR=999)XPHI
 
C Axis ratio :
	 READ(3,10,ERR=999)BUFFER
	 READ(3,*,ERR=999)AXRATIO
 
C Centre of the galaxy :
	 READ(3,10,ERR=999)BUFFER
	 READ(3,*,ERR=999)X0,Y0
 
C Jump 3 items in the file:
	 DO I=1,6
	  READ(3,10,ERR=999)BUFFER
	 END DO
 
C Sky level :
	 READ(3,10,ERR=999)BUFFER
	 READ(3,*,ERR=999)SKY
 
C Jump 1 item:
	 READ(3,10,ERR=999)BUFFER
	 READ(3,10,ERR=999)BUFFER
 
C Scale :
	 READ(3,10,ERR=999)BUFFER
	 READ(3,*,ERR=999)SCALE
 
C Jump the last 3 items :
	 DO I=1,6
	  READ(3,10,ERR=999)BUFFER
	 END DO
 
C Read the profile itself :
	  READ(3,*)NPTS
	  PRINT *,' NPTS =',NPTS
	  DO I=1,NPTS
	   READ(3,*) VRAD(I),VPRO(I),WORK
	  END DO
 
C Computing the first guess for UU,VV,WW : (Passed through COMMON/FIXELLIP)
    	CO=COS(XPHI*PI/180.)
	SI=SIN(XPHI*PI/180.)
	UU=CO*CO+(SI/AXRATIO)**2
	VV=SI*SI+(CO/AXRATIO)**2
	WW=2.*SI*CO*(1.-1./(AXRATIO*AXRATIO))
 
C Return
	CLOSE(3)
	RETURN
 
C Exit if error :
999	 PRINT *,' Error reading the profile'
	 STOP
 
	END
C*************************************************************
	include 'jlpsub:plagal_set.for'
	include 'jlpsub:polyfit.for'
