C++***************************************************************
C	PROGRAM REMSTAR
C
C Program REMSTAR to generate a file with the position and size of
C the defects, which can then be removed by "PATCH".
C In input needs the mask generated by "PROFILE1"
C           0=O.K.   1=aberrant point,  or reverse.
C
C SYNTAX:
C    RUNS REMSTAR input_mask output_list min_diam,max_diam
C
C Example:
C    RUNS REMSTAR test_mask test.pat 1.,30.
C
C Nota1: input_list is a file containing the list of positions and diameters
C        which will be used by "PATCH1".
C Nota2: min_diam,max_diam are the limits in diameters (pixels) for the patches
C        to be taken into account.
C
C JLP
C Version of 19/07/90
C--***************************************************************
	PROGRAM REMSTAR
	CHARACTER NAME*40,NAMEPAT*40,COMMENTS*80
	LOGICAL AUTOSKY,INTERAC
	LOGICAL AUTO_GUESS,AUTO_IMPROVE,FOURIER,KAMIKAZE
	LOGICAL LONGESTCONT,SKELETON
	INTEGER*4 MADRID(1),PNTR_INPUT
	COMMON /VMR/MADRID
 
C Common blocks with "CONTOUR_SET"
	COMMON/BLOCK9/ LMAX,NCON
	COMMON/CONTOUR1/XCENTRE(1000),YCENTRE(1000),RADIUS(1000),
     1	RADMIN,NCONT1,SKELETON
 
10	FORMAT(A)
 
	CALL JLP_BEGIN
 
C File with the details of the program execution
	OPEN(UNIT=9,FILE='remstar.log',
     1	ACCESS='SEQUENTIAL',STATUS='unknown')
 
	PRINT 102
102	FORMAT(' Program REMSTAR to generate a file compatible',
     1	' with "PATCH"',/,
     1	'  to remove the stars from an image.',/,
     1	' (In input needs the mask generated by "PROFILE1"',
     1	'     0=O.K.  1=aberrant point)',/,
     1	' Version of 19/07/90')
 
C Inquire the format of the files :
	CALL JLP_INQUIFMT
 
C Enters the input file
	PRINT *,' NAME OF THE INPUT IMAGE MASK:'
	READ(5,10) NAME
	CALL JLP_VM_READIMAG(PNTR_INPUT,NX,NY,NAME,COMMENTS)
 
	WRITE(9,63)NAME
63	FORMAT(2X,'NAME OF THE INPUT IMAGE :',A40,/)
 
53	PRINT *,' NAME OF THE OUTPUT LIST : '
	READ(5,10) NAMEPAT
 
C File with the output parameters
	OPEN(UNIT=11,FILE=NAMEPAT,
     1	ACCESS='SEQUENTIAL',STATUS='UNKNOWN',ERR=53)
 
C First level (0.5):
	CV=0.5
	LMAX=0
	NCON=0
	NCONT1=0
 
C Calling the subroutine to find the contour KV
	LONGESTCONT=.FALSE.
	SKELETON=.TRUE.
C	PRINT *,' MINIMUM RADIUS FOR THE PATCHES ?'
C	READ(5,*) RADMIN
	RADMIN=0.
	CALL GGROPE(MADRID(PNTR_INPUT),NX,NY,NX,OX,OY,CV,
     1	LONGESTCONT)
 
	WRITE(9,750) NCON,NCONT1
	WRITE(6,750) NCON,NCONT1
750	FORMAT(/,'******** THE LEVEL 0.5  CONTAINS',I6,
     1	' CONTOURS',/,
     1	' NUMBER OF SELECTED CONTOURS :',I8)
 
	PRINT *,' ENTER MIN AND MAX DIAMETERS FOR "PATCH"'
	READ(5,*) IDIAMIN,IDIAMAX
	WRITE(9,933)IDIAMIN,IDIAMAX
933	FORMAT(' MIN AND MAX DIAMETERS FOR "PATCH" :',2(I5,2X))
 
C We take a diameter = 3.5 * radius (radius of the initial spot), for "PATCH"
C When there was only one bad pixel, the radius is in the
C range 0.25 < R < 0.7 according to the value (for Masks, it is 0.5, ie DIAM=2)
C When there was only two bad pixels, the radius is 0.75 , IDIAM=4)
C 3.5 is a good compromise to get nice results with automatic patch.
	KK=0
	DO I=1,NCONT1
	  IXC=XCENTRE(I)
	  IYC=YCENTRE(I)
	  IDIAM=NINT(RADIUS(I)*3.5)
	 IF(IDIAM.GE.IDIAMIN.AND.IDIAM.LE.IDIAMAX)THEN
	   WRITE(11,*)IXC,IYC,IDIAM
	   KK=KK+1
	 ELSE
	   WRITE(9,934)IXC,IYC,IDIAM
934	   FORMAT(' REJECTED PATCH : ',3(I6,2X))
	 ENDIF
	END DO
 
	PRINT 935,KK
935	FORMAT(' NUMBER OF SELECTED PATCHES :',I8)
 
	CLOSE(9)
	CLOSE(11)
 
	PRINT 936
936	FORMAT(' Logfile in "remstar.log"')
	CALL JLP_END
	STOP
	END
C----------------------------------------------------------------------
	include 'jlpsub:contour_set.for'
